import { Contest } from './types'

function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().split('T')[0]
}

export const MOCK_CONTESTS: Contest[] = [
  {
    id: 'mock-1',
    title: 'Create a 30-Second Ad for Our New Running Shoe',
    brand: 'Apex Athletics',
    description: 'We are looking for video creators to produce a 30-second commercial for our upcoming running shoe. Your ad should capture energy, movement, and the spirit of pushing limits. Style: cinematic or fast-cut. Must include product footage (we will ship you a sample pair).',
    prize: '$1,000 cash',
    deadline: daysFromNow(21),
    category: 'Ad',
    source_platform: 'Instagram',
    source_url: '#',
    thumbnail_url: null,
    featured: true,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    title: 'Short Film Competition — "Unseen City"',
    brand: 'Urban Lens Festival',
    description: 'Show us the unseen side of the city you live in. Any city, any country. Max 5 minutes. We want raw, observational storytelling. No narration required. All formats accepted — phone, DSLR, film.',
    prize: '$2,500 + festival screening',
    deadline: daysFromNow(35),
    category: 'Short Film',
    source_platform: 'Website',
    source_url: '#',
    thumbnail_url: null,
    featured: true,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    title: 'Music Video Challenge: Indie Electronic Artists',
    brand: 'Wavefront Records',
    description: 'Wavefront Records is accepting music video submissions for three of our indie electronic artists. You pick the track, you direct the video. Best video wins a paid licensing deal and placement on our streaming channels.',
    prize: '$800 + sync license deal',
    deadline: daysFromNow(28),
    category: 'Music Video',
    source_platform: 'Twitter',
    source_url: '#',
    thumbnail_url: null,
    featured: true,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    title: 'Social Reel Contest: Show Your Morning Routine',
    brand: 'Brew Collective Coffee',
    description: 'How do you start your day? We want to see your morning routine featuring Brew Collective products. Best reel wins free coffee for a year plus $250. Post publicly and tag us.',
    prize: '$250 + 1yr free coffee',
    deadline: daysFromNow(3),
    category: 'Social',
    source_platform: 'Instagram',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    title: 'Cinematic Travel Reel — Southeast Asia',
    brand: 'NomadGear',
    description: 'Calling all travel filmmakers. Shoot a cinematic travel reel (60 seconds to 3 minutes) set anywhere in Southeast Asia. Focus on atmosphere, light, and local life. NomadGear will feature the winning video in their brand campaign.',
    prize: 'Gear package ($1,200 value) + brand feature',
    deadline: daysFromNow(42),
    category: 'Cinematic',
    source_platform: 'YouTube',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    title: 'Reddit r/filmmakers Annual Short Film Jam',
    brand: 'r/filmmakers Community',
    description: 'Annual 48-hour short film jam hosted by the r/filmmakers subreddit. Theme announced at start. Max 10 minutes. All skill levels welcome. Judged by community vote plus a panel of working directors.',
    prize: 'Community recognition + equipment prizes',
    deadline: daysFromNow(60),
    category: 'Short Film',
    source_platform: 'Reddit',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-7',
    title: 'Product Ad Challenge: Skincare Flat Lay Reel',
    brand: 'Glow Theory',
    description: 'Create a 15-30 second product reel for our skincare line using flat lay or tabletop cinematography. We will ship product to top applicants. Looking for that cool editorial aesthetic.',
    prize: '$400 + product gifting',
    deadline: daysFromNow(18),
    category: 'Ad',
    source_platform: 'Instagram',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-8',
    title: 'Drone Cinematography Contest',
    brand: 'SkyView Media',
    description: 'Submit your most stunning drone footage — landscapes, cityscapes, architecture, or events. Edit it into a 60-90 second cinematic piece. Any location worldwide.',
    prize: '$1,500 cash + feature in reel library',
    deadline: daysFromNow(30),
    category: 'Cinematic',
    source_platform: 'Website',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-9',
    title: 'Comedy Sketch Ad Competition',
    brand: 'Snack Riot',
    description: 'We make chaotic snacks for chaotic people. Make us a funny 30-60 second ad. Go absurd. The more unhinged the better. Will be shared on all our channels.',
    prize: '$600 cash + year supply of snacks',
    deadline: daysFromNow(25),
    category: 'Ad',
    source_platform: 'Twitter',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-10',
    title: 'YouTube Shorts Creator Challenge',
    brand: 'Pixelcraft Tools',
    description: 'Create a YouTube Short (under 60 seconds) demonstrating a creative use of our design tools. Show your workflow, a process video, or a before/after.',
    prize: '$300 + annual pro subscription',
    deadline: daysFromNow(20),
    category: 'Social',
    source_platform: 'YouTube',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-11',
    title: 'Mini-Documentary: "People Who Build Things"',
    brand: 'Workshop Magazine',
    description: 'Pitch and produce a 3-5 minute mini-documentary about someone who makes or builds things with their hands. Woodworkers, ceramicists, car restorers — anyone creating something physical.',
    prize: '$1,000 + print feature',
    deadline: daysFromNow(45),
    category: 'Short Film',
    source_platform: 'Website',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'open',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-12',
    title: 'Dance x Cinematography Collab Contest',
    brand: 'Rhythm Labs',
    description: 'Partner with a dancer (or be one yourself) and shoot a 60-90 second video that merges movement and filmmaking. We care about sync, visual language, and how the camera works with the body.',
    prize: '$750 + artist feature',
    deadline: daysFromNow(-5),
    category: 'Social',
    source_platform: 'Instagram',
    source_url: '#',
    thumbnail_url: null,
    featured: false,
    status: 'closed',
    submitted_by: null,
    approved: true,
    created_at: new Date().toISOString(),
  },
]

export const MOCK_FEATURED = MOCK_CONTESTS.filter((c) => c.featured)
export const MOCK_RECENT = MOCK_CONTESTS
